version: '3'
services:
  fashop:
    image: fashop/fashop:v2.0.0
    ports:
      - "9510:9510"
    volumes:
      - ./:/var/www/fashop
    stdin_open: true
    tty: true
    privileged: true
    entrypoint: ["php", "/var/www/fashop/fashop", "start"]

  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${MYSQL_DATA_DIR}:/var/lib/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  fashop-admin-build:
    image: ezkuangren/fashop-admin:latest
    environment:
      FASHOP_ADMIN_VERSION: "${FASHOP_ADMIN_VERSION}"
    volumes:
      - ${FASHOP_ADMIN_BUILD_DIR}:/fashop-admin-code
    tty: true
    privileged: true
    entrypoint: ["cp", "-r", "/fashop-admin/dist/","/fashop-admin-code"]

  fashop-dev:
    image: ezkuangren/swoole1
    container_name: fashop-dev
    ports:
      - "9511:9510"
    volumes:
      - ./:/var/www/project
    stdin_open: true
    tty: true
    privileged: true
