version: '3'
services:
  fashop:
    image: fashop/fashop:v2.0.0
    ports:
      - 9510:9510
    volumes:
      - ./:/var/www/fashop
    stdin_open: true
    tty: true
    privileged: true
    entrypoint: ["php", "/var/www/fashop/fashop", "start"]

  fashop-dev:
    image: ezkuangren/swoole1
    ports:
      - "9511:9510"
    volumes:
      - ./:/var/www/project
    stdin_open: true
    tty: true
    privileged: true
