version: '3'

services:
    fashop:
       image: fashop/fashop:v1.0.0
#       build: ./
       ports:
         - "9510:9510"
       volumes:
         - ./:/var/www/fashop
       stdin_open: true
       tty: true
       privileged: true
       entrypoint: ["php", "/var/www/fashop/fashop", "start"]
